class Item < ActiveRecord::Base
  attr_accessible :ndb_no
  attr_accessible :water_gper100g
  attr_accessible :energy_kcal_per_100g
  attr_accessible :protein_gper100g 
  attr_accessible :lipid_gper100g 
  attr_accessible :ash_gper100g 
  attr_accessible :carbohydrate_gper100g 
  attr_accessible :fibre_gper100g 
  attr_accessible :sugar_gper100g 
  attr_accessible :calcium_mgper100g 
  attr_accessible :iron_mgper100g 
  attr_accessible :magnesium_mgper100g 
  attr_accessible :phosphorus_mgper100g 
  attr_accessible :potassium_mgper100g 
  attr_accessible :sodium_mgper100g 
  attr_accessible :zinc_mgper100g 
  attr_accessible :copper_mgper100g 
  attr_accessible :manganese_mgper100g 
  attr_accessible :selenium_ugper100g 
  attr_accessible :vitamin_c_mgper100g 
  attr_accessible :thiamin_mgper100g 
  attr_accessible :riboflavin_mgper100g 
  attr_accessible :niacin_mgper100g 
  attr_accessible :panto_acid_mgper100g 
  attr_accessible :vitamin_b6_mgper100g 
  attr_accessible :folate_total_ugper100g 
  attr_accessible :folate_acid_ugper100g 
  attr_accessible :folate_food_ugper100g 
  attr_accessible :folate_dfe_ug_dfe_per100g 
  attr_accessible :choline_mgper100g 
  attr_accessible :vitamin_b12_ugper100g 
  attr_accessible :vitamin_a_iuper100g 
  attr_accessible :vitamin_a_ug_raeper100g 
  attr_accessible :retinol_ugper100g 
  attr_accessible :alpha_carotene_ugper100g 
  attr_accessible :beta_carotene__ugper100g 
  attr_accessible :beta_cryptoxanthin_ugper100g 
  attr_accessible :lycopene_ugper100g 
  attr_accessible :lutein_and_zeazanthin_ugper100g 
  attr_accessible :vitamin_e_mgper100g 
  attr_accessible :vitamin_d_ugper100g 
  attr_accessible :vitamin_d_iuper100g 
  attr_accessible :vitamin_k_ugper100g 
  attr_accessible :saturated_fatty_acid_mgper100g 
  attr_accessible :monounsaturated_fatty_acid_mgper100g 
  attr_accessible :polyunsaturated_fatty_acid_mgper100g 
  attr_accessible :cholesterol_mgper100g 
  attr_accessible :refuse_percent
  attr_accessible :description
  attr_accessible :food_group
end